@startuml
'https://plantuml.com/class-diagram

class Location {
double lat
double lng
}

class Santa {
Location home
List<Visit> visits
}

class Visit {
String id
String name
Location location
}


Santa -> Visit
Santa --> Location
Visit --> Location

@enduml